// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_q9IIuj0JvmEx-aZZ7wd4FJdPAsbEzhs',
    appId: '1:709880650894:web:eb660ef2caf973e143fddf',
    messagingSenderId: '709880650894',
    projectId: 'fresh-veggies-3e00b',
    authDomain: 'fresh-veggies-3e00b.firebaseapp.com',
    storageBucket: 'fresh-veggies-3e00b.firebasestorage.app',
    measurementId: 'G-LTW9WHQZ7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTG8txRdP51kKKdSMrOJDOYuALMkOJyw4',
    appId: '1:709880650894:android:428081cca94f726e43fddf',
    messagingSenderId: '709880650894',
    projectId: 'fresh-veggies-3e00b',
    storageBucket: 'fresh-veggies-3e00b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa75z6omO5-eJEdWSZ33_JArSBPx-GeVA',
    appId: '1:709880650894:ios:2278311dbce3332043fddf',
    messagingSenderId: '709880650894',
    projectId: 'fresh-veggies-3e00b',
    storageBucket: 'fresh-veggies-3e00b.firebasestorage.app',
    iosBundleId: 'com.example.freshVeggies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa75z6omO5-eJEdWSZ33_JArSBPx-GeVA',
    appId: '1:709880650894:ios:2278311dbce3332043fddf',
    messagingSenderId: '709880650894',
    projectId: 'fresh-veggies-3e00b',
    storageBucket: 'fresh-veggies-3e00b.firebasestorage.app',
    iosBundleId: 'com.example.freshVeggies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_q9IIuj0JvmEx-aZZ7wd4FJdPAsbEzhs',
    appId: '1:709880650894:web:13eeb6187684249443fddf',
    messagingSenderId: '709880650894',
    projectId: 'fresh-veggies-3e00b',
    authDomain: 'fresh-veggies-3e00b.firebaseapp.com',
    storageBucket: 'fresh-veggies-3e00b.firebasestorage.app',
    measurementId: 'G-DRW6Z9J17J',
  );
}
